routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', '/apps/accounting');
Route::redirect('/apps', '/apps/accounting')->name('apps');

Route::view('/contact', 'contact')->name('contact');

Route::prefix('/apps')->name('apps.')->group(function () {
    Route::view('accounting', 'apps.categories.accounting')->name('accounting');
    Route::view('secretary', 'apps.categories.secretary')->name('secretary');
    Route::view('sales', 'apps.categories.sales')->name('sales');
    Route::view('multimedia', 'apps.categories.multimedia')->name('multimedia');
});

Route::view('/dashboard', 'dashboard')->middleware(['auth'])->name('dashboard');

resources/views/apps/footer-new-function.blade.php
 <div class="max-w-7xl mx-auto pt-4 px-4 sm:px-6 md:flex md:items-center md:justify-between lg:px-8">
        <div class="flex flex-1 justify-center space-x-6 md:order-2">
            <a href="/contact?reason=new-app" class="text-gray-400 hover:text-gray-600 hover:underline">
                {{ __("Didn't find what you are looking for?") }}
                <br class="sm:hidden">
                {{ __('Request new function.') }}
            </a>
    </div>
 </div>

resources/views/apps/layout.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    {{-- Fonts --}}
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

    {{-- Styles --}}
    <link rel="stylesheet" href="{{ mix('css/app.css') }}">

    @livewireStyles

    {{-- Scripts --}}
    <script src="{{ mix('js/app.js') }}" defer></script>
</head>
<body class="font-sans antialiased">
    <div class="h-screen flex overflow-hidden bg-gray-100 main-pattern"
         x-data="{ isSidebarOpen: false }"
    >
        @include('apps.sidebar')

{{--        <svg class="absolute h-screen w-screen top-0 left-0"  fill="none" viewBox="0 0 500 500">--}}
{{--            <defs>--}}
{{--                <pattern id="837c3e70-6c3a-44e6-8854-cc48c737b659" x="0" y="0" width="20" height="20" patternUnits="userSpaceOnUse">--}}
{{--                    <rect x="0" y="0" width="4" height="4" class="text-gray-200" fill="currentColor"></rect>--}}
{{--                </pattern>--}}
{{--            </defs>--}}
{{--            <rect class="h-full w-full" width="1000" height="1000" fill="url(#837c3e70-6c3a-44e6-8854-cc48c737b659)"></rect>--}}
{{--        </svg>--}}

        <div class="flex flex-col w-0 flex-1 overflow-y-auto">
            @include('apps.topbar')

            {{-- Page Content --}}
            {{ $slot }}

            @livewire('cookie-policy')
        </div>

    </div>

    @stack('modals')

    @livewireScripts
</body>
</html>

resources/views/apps/sidebar.blade.php
{{-- Off-canvas menu for mobile, show/hide based on off-canvas menu state. --}}
<div class="fixed inset-0 flex z-40 md:hidden" role="dialog" aria-modal="true"
     x-show="isSidebarOpen"
     :aria-hidden="!isSidebarOpen"
     :aria-expanded="isSidebarOpen"
>
    {{--
      Off-canvas menu overlay, show/hide based on off-canvas menu state.

      Entering: "transition-opacity ease-linear duration-300"
        From: "opacity-0"
        To: "opacity-100"
      Leaving: "transition-opacity ease-linear duration-300"
        From: "opacity-100"
        To: "opacity-0"
    --}}
    <div class="fixed inset-0 bg-gray-600 bg-opacity-75"
         x-show="isSidebarOpen"
         x-transition:enter="transition-opacity ease-linear duration-300"
         x-transition:enter-start="opacity-0"
         x-transition:enter-end="opacity-100"
         x-transition:leave="transition-opacity ease-linear duration-300"
         x-transition:leave-start="opacity-100"
         x-transition:leave-end="opacity-0"
    ></div>

    {{--
      Off-canvas menu, show/hide based on off-canvas menu state.

      Entering: "transition ease-in-out duration-300 transform"
        From: "-translate-x-full"
        To: "translate-x-0"
      Leaving: "transition ease-in-out duration-300 transform"
        From: "translate-x-0"
        To: "-translate-x-full"
    --}}
    <div class="relative flex-1 flex flex-col max-w-xs w-full pt-5 pb-4 bg-indigo-700"
         x-show="isSidebarOpen"
         x-transition:enter="transition ease-in-out duration-300 transform"
         x-transition:enter-start="-translate-x-full"
         x-transition:enter-end="translate-x-0"
         x-transition:leave="transition ease-in-out duration-300 transform"
         x-transition:leave-start="translate-x-0"
         x-transition:leave-end="-translate-x-full"
    >
        {{--
          Close button, show/hide based on off-canvas menu state.

          Entering: "ease-in-out duration-300"
            From: "opacity-0"
            To: "opacity-100"
          Leaving: "ease-in-out duration-300"
            From: "opacity-100"
            To: "opacity-0"
        --}}
        <div class="absolute top-0 right-0 -mr-12 pt-2"
             x-show="isSidebarOpen"
             x-transition:enter="ease-in-out duration-300"
             x-transition:enter-start="opacity-0"
             x-transition:enter-end="opacity-100"
             x-transition:leave="ease-in-out duration-300"
             x-transition:leave-start="opacity-100"
             x-transition:leave-end="opacity-0"
        >
            <button type="button" class="ml-1 flex items-center justify-center h-10 w-10 rounded-full focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white"
                    @click="isSidebarOpen = false"
                    x-show="isSidebarOpen"
            >
                <span class="sr-only">Close sidebar</span>
                <svg class="h-6 w-6 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/>
                </svg>
            </button>
        </div>

        <div class="flex-shrink-0 flex items-center px-4">
            <img class="h-8 w-auto" src="https://tailwindui.com/img/logos/workflow-logo-indigo-300-mark-white-text.svg" alt="Workflow">
        </div>
        <div class="mt-5 flex-1 flex flex-col overflow-y-auto">
            <nav class="flex-1 px-2 space-y-1">
                <x-jet-apps-category-link href="{{ route('apps.accounting') }}" :active="request()->routeIs('apps.accounting')" :mobile="true">
                    <svg class="mr-4 h-6 w-6 text-indigo-300" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 7h6m0 10v-3m-3 3h.01M9 17h.01M9 14h.01M12 14h.01M15 11h.01M12 11h.01M9 11h.01M7 21h10a2 2 0 002-2V5a2 2 0 00-2-2H7a2 2 0 00-2 2v14a2 2 0 002 2z"/>
                    </svg>
                    {{ __('Accounting') }}
                </x-jet-apps-category-link>

                <x-jet-apps-category-link href="{{ route('apps.secretary') }}" :active="request()->routeIs('apps.secretary')" :mobile="true">
                    <svg class="mr-4 h-6 w-6 text-indigo-300" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 8h14M5 8a2 2 0 110-4h14a2 2 0 110 4M5 8v10a2 2 0 002 2h10a2 2 0 002-2V8m-9 4h4"/>
                    </svg>
                    {{ __('Secretary') }}
                </x-jet-apps-category-link>

{{--                <x-jet-apps-category-link href="{{ route('apps.sales') }}" :active="request()->routeIs('apps.sales')" :mobile="true">--}}
{{--                    <svg class="mr-4 h-6 w-6 text-indigo-300" fill="none" viewBox="0 0 24 24" stroke="currentColor">--}}
{{--                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 12l3-3 3 3 4-4M8 21l4-4 4 4M3 4h18M4 4h16v12a1 1 0 01-1 1H5a1 1 0 01-1-1V4z"/>--}}
{{--                    </svg>--}}
{{--                    {{ __('Sales') }}--}}
{{--                </x-jet-apps-category-link>--}}

                <x-jet-apps-category-link href="{{ route('apps.multimedia') }}" :active="request()->routeIs('apps.multimedia')" :mobile="true">
                    <svg class="mr-4 h-6 w-6 text-indigo-300" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 10l4.553-2.276A1 1 0 0121 8.618v6.764a1 1 0 01-1.447.894L15 14M5 18h8a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v8a2 2 0 002 2z"></path>
                    </svg>
                    {{ __('Multimedia') }}
                </x-jet-apps-category-link>
            </nav>

            <div class="space-y-1">
                <h3 class="px-3 text-xs font-semibold text-gray-500 uppercase tracking-wider ">
                    <br>
                </h3>
                <div class="space-y-1" role="group">

                    <a href="mailto:vardtheo@theograms.tech" class="group flex items-center px-3 py-2 text-sm font-medium text-indigo-200 rounded-md hover:text-white">
                        <span class="truncate">
                            {{ __('Contact') }}
                        </span>
                    </a>

                    <a href="{{ route('policy.show') }}" class="group flex items-center px-3 py-2 text-sm font-medium text-indigo-200 rounded-md hover:text-white">
                        <span class="truncate">
                            {{ __('Privacy Policy') }}
                        </span>
                    </a>

                    {{--                    <a href="{{ route('terms.show') }}" class="group flex items-center px-3 py-2 text-sm font-medium text-indigo-200 rounded-md hover:text-white">--}}
                    {{--                        <span class="truncate">--}}
                    {{--                            {{ __('Terms of Service') }}--}}
                    {{--                        </span>--}}
                    {{--                    </a>--}}

                </div>
            </div>
        </div>
    </div>

    <div class="flex-shrink-0 w-14" aria-hidden="true">
        {{-- Dummy element to force sidebar to shrink to fit close icon --}}
    </div>
</div>

{{-- Static sidebar for desktop --}}
<div class="hidden bg-indigo-700 md:flex md:flex-shrink-0">
    <div class="flex flex-col w-64">

        <div class="flex flex-col flex-grow pt-5 pb-4 overflow-y-auto">
            <div class="flex items-center flex-shrink-0 px-4">
                <img class="h-8 w-auto" src="https://tailwindui.com/img/logos/workflow-logo-indigo-300-mark-white-text.svg" alt="Workflow">
            </div>
            <div class="mt-5 flex-1 flex flex-col">
                <nav class="flex-1 px-2 space-y-1">
                    <x-jet-apps-category-link href="{{ route('apps.accounting') }}" :active="request()->routeIs('apps.accounting')">
                        <svg class="mr-4 h-6 w-6 text-indigo-300" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 7h6m0 10v-3m-3 3h.01M9 17h.01M9 14h.01M12 14h.01M15 11h.01M12 11h.01M9 11h.01M7 21h10a2 2 0 002-2V5a2 2 0 00-2-2H7a2 2 0 00-2 2v14a2 2 0 002 2z"/>
                        </svg>
                        {{ __('Accounting') }}
                    </x-jet-apps-category-link>

                    <x-jet-apps-category-link href="{{ route('apps.secretary') }}" :active="request()->routeIs('apps.secretary')">
                        <svg class="mr-4 h-6 w-6 text-indigo-300" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 8h14M5 8a2 2 0 110-4h14a2 2 0 110 4M5 8v10a2 2 0 002 2h10a2 2 0 002-2V8m-9 4h4"/>
                        </svg>
                        {{ __('Secretary') }}
                    </x-jet-apps-category-link>

{{--                    <x-jet-apps-category-link href="{{ route('apps.sales') }}" :active="request()->routeIs('apps.sales')">--}}
{{--                        <svg class="mr-4 h-6 w-6 text-indigo-300" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">--}}
{{--                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 12l3-3 3 3 4-4M8 21l4-4 4 4M3 4h18M4 4h16v12a1 1 0 01-1 1H5a1 1 0 01-1-1V4z"/>--}}
{{--                        </svg>--}}
{{--                        {{ __('Sales') }}--}}
{{--                    </x-jet-apps-category-link>--}}

                    <x-jet-apps-category-link href="{{ route('apps.multimedia') }}" :active="request()->routeIs('apps.multimedia')" :mobile="true">
                        <svg class="mr-4 h-6 w-6 text-indigo-300" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 10l4.553-2.276A1 1 0 0121 8.618v6.764a1 1 0 01-1.447.894L15 14M5 18h8a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v8a2 2 0 002 2z"></path>
                        </svg>
                        {{ __('Multimedia') }}
                    </x-jet-apps-category-link>
                </nav>

                <div class="space-y-1">
                    <h3 class="px-3 text-xs font-semibold text-gray-500 uppercase tracking-wider ">
                        <br>
                    </h3>
                    <div class="space-y-1" role="group">

                        <a href="mailto:vardtheo@gmail.com" class="group flex items-center px-3 py-2 text-sm font-medium text-indigo-200 rounded-md hover:text-white">
                            <span class="truncate">
                                {{ __('Contact') }}
                            </span>
                        </a>

                        <a href="{{ route('policy.show') }}" class="group flex items-center px-3 py-2 text-sm font-medium text-indigo-200 rounded-md hover:text-white">
                            <span class="truncate">
                                {{ __('Privacy Policy') }}
                            </span>
                        </a>

                        {{--                        <a href="{{ route('terms.show') }}" class="group flex items-center px-3 py-2 text-sm font-medium text-indigo-200 rounded-md hover:text-white">--}}
                        {{--                            <span class="truncate">--}}
                        {{--                                {{ __('Terms of Service') }}--}}
                        {{--                            </span>--}}
                        {{--                        </a>--}}

                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

resources/views/apps/topbar.blade.php
<div class="relative z-10 flex-shrink-0 flex h-16 bg-white shadow">
    <button type="button" class="px-4 border-r border-gray-200 text-gray-500 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500 md:hidden"
            @click="isSidebarOpen = true;"
            x-show="!isSidebarOpen"
            @click.away="isSidebarOpen = false"
    >
        <span class="sr-only">Open sidebar</span>
        {{-- Heroicon name: outline/menu-alt-2 --}}
        <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h7"/>
        </svg>
    </button>
    <div class="flex-1 px-4 flex justify-between">
        <div class="flex-1 flex">
{{--            <form class="w-full flex md:ml-0" action="#" method="GET">--}}
{{--                <label for="search_field" class="sr-only">Search</label>--}}
{{--                <div class="relative w-full text-gray-400 focus-within:text-gray-600">--}}
{{--                    <div class="absolute inset-y-0 left-0 flex items-center pointer-events-none">--}}
{{--                        <svg class="h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">--}}
{{--                            <path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd"/>--}}
{{--                        </svg>--}}
{{--                    </div>--}}
{{--                    <input id="search_field" class="block w-full h-full pl-8 pr-3 py-2 border-transparent text-gray-900 placeholder-gray-500 focus:outline-none focus:placeholder-gray-400 focus:ring-0 focus:border-transparent sm:text-sm" placeholder="Search" type="search" name="search">--}}
{{--                </div>--}}
{{--            </form>--}}
        </div>
        <div class="ml-4 flex items-center md:ml-6">
            {{--            <button class="bg-white p-1 rounded-full text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">--}}
            {{--                <span class="sr-only">View notifications</span>--}}
            {{--                <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">--}}
            {{--                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9"/>--}}
            {{--                </svg>--}}
            {{--            </button>--}}

            {{-- Profile dropdown --}}
            @auth
                <x-jet-profile-dropdown/>
            @else
                <div class="flex items-center md:ml-12">
                    <a href="{{ route('login') }}" class="text-base font-medium text-gray-500 hover:text-gray-900">
                        {{ __('Sign in') }}
                    </a>
                    <a href="{{ route('register') }}" class="ml-8 inline-flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-indigo-600 hover:bg-indigo-700">
                        {{ __('Sign up') }}
                    </a>
                </div>
            @endauth

        </div>
    </div>
</div>